#!/bin/bash

LOCK=" Lock"
LOGOUT="󰍃 Logout"
SUSPEND="󰤄 Suspend"
REBOOT="󰜉 Reboot"
SHUTDOWN="󰐥 Power Off"

CHOICE=$(printf "%s\n%s\n%s\n%s\n%s" "$LOCK" "$LOGOUT" "$SUSPEND" "$REBOOT" "$SHUTDOWN" | wofi --dmenu --prompt "Power Menu" --width 300 --height 300)

case "$CHOICE" in
    "$LOCK")
        hyprlock ;;
    "$LOGOUT")
	hyprctl dispatch "hl.dsp.exit()" ;;
    "$SUSPEND")
        systemctl suspend ;;
    "$REBOOT")
        systemctl reboot ;;
    "$SHUTDOWN")
        systemctl poweroff ;;
esac
