animations {
	enabled = true
	animation = inputFieldColors, 1, 2, linear
}

background {
	path = screenshot
	color = rgba(32, 0, 32, 0.9)
	brightness = 0.5

	blur_passes = 3
	blur_size = 7
}

# Top-right info

label {
	position = -25, -25
	halign = right
	valign = top

	text = cmd[] uname -n
	color = rgb(255, 255, 255)
	font_size = 12
}

label {
	position = -25, -50
	halign = right
	valign = top

	text = cmd[] echo "$(uname -s) $(uname -r)"
	color = rgb(255, 255, 255)
	font_size = 12
}

label {
	position = -25, -75
	halign = right
	valign = top

	text = cmd[update:1000] date +"%Y-%m-%d"
	color = rgb(255, 255, 255)
	font_size = 12
}

label {
	position = -25, -100
	halign = right
	valign = top

	text = cmd[update:1000] ~/.local/bin/tze-battery-status 
	color = rgb(255, 255, 255)
	font_size = 12
}

# Main content

label {
	position = 0, 100

	text = $TIME12
	color = rgb(255, 255, 255)
	font_size = 64
}

input-field {
	size = 400, 75
	position = 0, -50

	outline_thickness = 3

	outer_color = rgb(128, 0, 128)
	inner_color = rgb(64, 0, 64)
	font_color = rgb(255, 255, 255)

	fade_on_empty = false

	placeholder_text =
	check_color = rgb(128, 128, 128)
	fail_color = rgb(255, 0, 0)
	fail_text =

	capslock_color = rgb(255, 255, 0)
}
